### ISSUE TITLE
Editor TODO

### ISSUE THREAD

**Issue by FoLoKe** [FoLoKe/SCU#13]
![sketch1642753103976](https://user-images.githubusercontent.com/36813380/150495039-bd388a16-d454-447f-9f2d-19644e159900.png)
- [	] window layout
	- [ ] controlls pane
		- [ ] save button icon
		- [ ] load button icon
		- [ ] exit button icon
	- [ ] left pane
		- [ ] brush icon
		- [ ] picker icon
		- [ ] erasier icon
		- [x] pallet (Color picker widget)
	- [ ] right pane
		- [ ] module widget
		- [ ] categories list
		- [ ] info box widget
- [x] grid shader
- [ ] new button functionality (ship bridge preset dialog or new module tabbed dialog)
- [ ] save/load buttons functionality
- [ ] color picker/pallet functionality (for selected colorset)
- [ ] eraiser functionality
- [ ] brush functionality
- [ ] modules load and categorization
- [ ] modules placement (overwrite checkbox)
- [ ] overlay functionality
- [ ] overlay button functionality
- [ ] zoom in/out
- [ ] drag
- [ ] exit confirmation dialog
- [ ] stats calculation
- [ ] info box functionality
